spring:
  application:
    name: apiGateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employeeModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: lb://CUSTOMER
          predicates:
            - Path=/customer/**
eureka:
  client:
    service-url:
      defualt-zone: http://localhost:8761/eureka
server:
  port: 8080


